config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  resources :posts
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < InheritedResources::Base
  before_action :authenticate_member!, except: [:index,:show]
  def new
    @post=Post.new
  end
  def create
    @post = Post.new(post_params)
    # @post.area=post_params['area']
    @post.save
    redirect_to @post
    # render plain: params[:post].inspect
  end
  def show
    @post = Post.find(params[:id])
  end

  def index
    @posts=Post.all
  end

  private

    def post_params
      params.require(:post).permit(:kind, :area, :price, :address, :lang, :lat, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Newakarmap</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%if member_signed_in?%>
      <%= link_to 'Sign Out', '/members/sign_out',
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %>
  <%end%>

</head>
<body>
</div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br>
    <%= f.select(:kind, options_for_select([['apartment', 'apartment'], ['villa', 'villa']])) %>
  </div>
  <div class="field">
    <%= f.label :area %><br>
    <%= f.text_field :area %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :lang %><br>
    <%= f.text_field :lang %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Area</th>
      <th>Price</th>
      <th>Address</th>
      <th>Lang</th>
      <th>Lat</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.kind %></td>
        <td><%= post.area %></td>
        <td><%= post.price %></td>
        <td><%= post.address %></td>
        <td><%= post.lang %></td>
        <td><%= post.lat %></td>
        <td><%= image_tag post.avatar.url(:thumb) %></td>
        <td><%= link_to 'Show', post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%if member_signed_in?%>
<%= link_to 'New Post', new_post_path %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @post.kind %>
</p>

<p>
  <strong>Area:</strong>
  <%= @post.area %>
</p>

<p>
  <strong>Price:</strong>
  <%= @post.price %>
</p>

<p>
  <strong>Address:</strong>
  <%= @post.address %>
</p>

<p>
  <strong>Lang:</strong>
  <%= @post.lang %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @post.lat %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @post.avatar.url %>
  <%= image_tag @post.avatar.url(:medium) %>
  <%= image_tag @post.avatar.url(:thumb) %>
</p>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>
<script>
//handler = Gmaps.build('Google');
//handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
//markers = handler.addMarkers([
//{
//
//"lat": ,
//"lng": ,
//"picture": {
//"url": "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
//"width":  36,
//"height": 36,
//    position: new google.maps.LatLng(30, 30)
//},
//"infowindow": "hello!"
//}
//]);
//handler.bounds.extendWith(markers);
//handler.fitMapToBounds();
//});
function initialize() {
    var myLatlng = new google.maps.LatLng(<%= @post.lat %>,<%= @post.lang %>);
    var mapOptions = {
        zoom: 8,
        center: myLatlng
    }
    var map = new google.maps.Map(document.getElementById('map'), mapOptions);

    var marker = new google.maps.Marker({
        position: myLatlng,
        map: map
    });
}

google.maps.event.addDomListener(window, 'load', initialize);
</script>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>